[package]
name = "ribm-testing"
version = { workspace = true }
edition = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
readme = "README.md"
description = { workspace = true }
repository = "https://github.com/devmcsam/ribm/crates/ribm-testing"
homepage = "https://github.com/devmcsam/ribm/crates/ribm-testing"
publish = false

[dependencies]
